import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import DefaultLayout from "../layouts/default";
import Viewer from "../components/viewer";

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <>
        <Head>
          <title>Alviz</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Viewer />
      </>

    </DefaultLayout>
  )
}

export default Home
