import React from 'react';
import type {NextPage} from 'next';
import Head from 'next/head';
import DefaultLayout from '../layouts/default';
import Viewer from '../components/viewer';

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <>
        <Head>
          <title>Alviz - Sorting Algorithm Visualizer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Viewer />
      </>

    </DefaultLayout>
  );
};

export default Home;
